name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  create-release:
    name: Build and Create Tagged release
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - name: Install archive tools
        run: sudo apt-get install -y zip

      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9.7.0

      - name: Install & Build Web UI
        working-directory: ./web
        run: |
          pnpm install
          pnpm build

      - name: Get variables & Tag Message
        id: get_vars
        run: |
          echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          echo "DATE=$(date +'%d-%m-%Y')" >> $GITHUB_ENV

          TAG_MSG=$(git tag -l --format='%(contents)' ${{ github.ref_name }})

          if [ -z "$TAG_MSG" ]; then
            TAG_MSG="${{ github.event.head_commit.message }}"
          fi

          {
            echo 'CHANGELOG<<EOF'
            echo "$TAG_MSG"
            echo 'EOF'
          } >> $GITHUB_ENV

          if [[ "${{ github.ref_name }}" == *"-"* ]]; then
            echo "IS_PRERELEASE=true" >> $GITHUB_ENV
          else
            echo "IS_PRERELEASE=false" >> $GITHUB_ENV
          fi

      - name: Bump manifest version
        run: node .github/actions/bump-manifest-version.js
        env:
          TGT_RELEASE_VERSION: ${{ github.ref_name }}

      - name: Push manifest change
        uses: EndBug/add-and-commit@v9
        with:
          add: fxmanifest.lua
          push: true
          author_name: Manifest Bumper
          author_email: 41898282+github-actions[bot]@users.noreply.github.com
          message: "chore: bump manifest version to ${{ github.ref_name }}"

      - name: Update tag ref
        uses: EndBug/latest-tag@latest
        with:
          tag-name: ${{ github.ref_name }}

      - name: Bundle files
        run: |
          mkdir -p ./temp/mbt_minigames

          cp ./{README.md,config.lua,fxmanifest.lua} ./temp/mbt_minigames/

          cp -r ./{core,modules} ./temp/mbt_minigames/

          mkdir -p ./temp/mbt_minigames/web
          cp -r ./web/dist ./temp/mbt_minigames/web/

          cd ./temp && zip -r ../mbt_minigames.zip ./mbt_minigames

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: mbt_minigames.zip
          name: ${{ github.ref_name }}
          body: ${{ env.CHANGELOG }}
          prerelease: ${{ env.IS_PRERELEASE }}
